// <auto-generated />
using System;
using Adventure.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adventure.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdventureDbContext))]
    [Migration("20260309230740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Adventure.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CurrentZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterFactionReputation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Standing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterFactionReputations");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterKnownSpell", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "SpellId");

                    b.ToTable("CharacterKnownSpells");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterProfession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterProfessions");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentObjectiveIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterQuests");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AIStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companions");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.EquippedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "SlotType")
                        .IsUnique();

                    b.ToTable("EquippedItems");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconSprite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.InventorySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventorySlots");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LootTables");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DropChance")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootTableEntries");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AIStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChallengeRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DialogueTree")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMerchant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQuestGiver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Profession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestGiverNpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReputationReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardGold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RewardItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("QuestGiverNpcId");

                    b.HasIndex("RewardItemId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.QuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectiveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestObjectives");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CraftingTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredSkillLevel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SkillGainChance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutputItemId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.SaveGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlayTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaveGames");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyPriceModifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellPriceModifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpcId")
                        .IsUnique();

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.ShopInventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceOverride")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopInventoryEntries");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealingDice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SavingThrowAbility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("School")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionData")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInteractable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWalkable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TilesetSpriteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "X", "Y")
                        .IsUnique();

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorldMapX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorldMapY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.ZoneConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FromZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromZoneId");

                    b.HasIndex("ToZoneId");

                    b.ToTable("ZoneConnections");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Consumable", b =>
                {
                    b.HasBaseType("Adventure.Domain.Entities.Item");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectValue")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CraftingMaterial", b =>
                {
                    b.HasBaseType("Adventure.Domain.Entities.Item");

                    b.Property<string>("MaterialCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CraftingMaterial");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Equipment", b =>
                {
                    b.HasBaseType("Adventure.Domain.Entities.Item");

                    b.Property<int?>("ArmorBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatBonuses")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterFactionReputation", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Character", null)
                        .WithMany("Reputations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterProfession", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Character", null)
                        .WithMany("Professions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.CharacterQuest", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Character", null)
                        .WithMany("Quests")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.EquippedItem", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Character", "Character")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.InventorySlot", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.LootTableEntry", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.LootTable", null)
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Monster", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Npc", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adventure.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Quest", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adventure.Domain.Entities.Npc", null)
                        .WithMany()
                        .HasForeignKey("QuestGiverNpcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Adventure.Domain.Entities.QuestObjective", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Quest", null)
                        .WithMany("Objectives")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("OutputItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Profession", null)
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Shop", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Npc", "Npc")
                        .WithOne("Shop")
                        .HasForeignKey("Adventure.Domain.Entities.Shop", "NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.ShopInventoryEntry", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Shop", "Shop")
                        .WithMany("Inventory")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Tile", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Zone", "Zone")
                        .WithMany("Tiles")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.ZoneConnection", b =>
                {
                    b.HasOne("Adventure.Domain.Entities.Zone", null)
                        .WithMany("Connections")
                        .HasForeignKey("FromZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adventure.Domain.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("ToZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Character", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Inventory");

                    b.Navigation("Professions");

                    b.Navigation("Quests");

                    b.Navigation("Reputations");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Npc", b =>
                {
                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Quest", b =>
                {
                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Shop", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Adventure.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
